"""Script to generate realistic, properly quoted demo menu data for Pakistani restaurants."""

import csv
import json
from pathlib import Path

DEMO_RECORDS = [
    {
        "id": "dish_001",
        "restaurant_name": "Monal Express",
        "dish_name": "Grilled Chicken Breast Bowl",
        "description": "Char-grilled chicken breast served with steamed brown rice and sauteed seasonal vegetables",
        "ingredients": "chicken breast, brown rice, olive oil, lemon, cumin, black pepper, seasonal vegetables",
        "price_pkr": 1150,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps([]),
        "category": "Chicken",
        "protein_g": 42,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Monal Express Gulberg Menu 2026",
        "source_url": "https://monal.demo.pk/menu/001",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_002",
        "restaurant_name": "Haveli Restaurant",
        "dish_name": "Murgh Makhani Butter Chicken",
        "description": "Tender chicken cooked in a rich creamy tomato gravy with butter and cashew paste",
        "ingredients": "chicken, butter, dairy cream, tomatoes, cashew paste, fenugreek, ginger, garlic",
        "price_pkr": 1450,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["dairy", "tree nuts"]),
        "category": "Chicken",
        "protein_g": 32,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Haveli Restaurant Menu 2026",
        "source_url": "https://haveli.demo.pk/menu/002",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_003",
        "restaurant_name": "Shinwari Dera",
        "dish_name": "Peshawari Chicken Karahi",
        "description": "Authentic Khyber style wok-cooked chicken with fresh tomatoes green chilies and black pepper",
        "ingredients": "chicken, fresh tomatoes, ginger, green chilies, black pepper, salt, animal fat",
        "price_pkr": 1350,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps([]),
        "category": "Chicken",
        "protein_g": 38,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Shinwari Dera Gulberg 2026",
        "source_url": "https://shinwari.demo.pk/menu/003",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_004",
        "restaurant_name": "Pan Asian Cloud Kitchen",
        "dish_name": "Chicken Satay Skewers",
        "description": "Flame grilled skewered chicken served with rich spicy peanut dipping sauce",
        "ingredients": "chicken breast, peanut sauce, roasted peanuts, soy sauce, garlic, sesame oil, chili",
        "price_pkr": 1200,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["peanuts", "soy"]),
        "category": "Chicken",
        "protein_g": 36,
        "availability": True,
        "cuisine": "Pan Asian",
        "source": "Pan Asian Kitchen Menu 2026",
        "source_url": "https://panasian.demo.pk/menu/004",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_005",
        "restaurant_name": "Salt & Pepper Village",
        "dish_name": "Premium Wagyu Beef Steak",
        "description": "Thick cut tender beef steak seared in garlic herb butter with mashed potatoes",
        "ingredients": "wagyu beef, butter, garlic, rosemary, potatoes, black pepper",
        "price_pkr": 3200,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps(["dairy"]),
        "category": "Beef",
        "protein_g": 55,
        "availability": True,
        "cuisine": "Continental",
        "source": "Salt & Pepper Menu 2026",
        "source_url": "https://snp.demo.pk/menu/005",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_006",
        "restaurant_name": "Expat Club Bistro",
        "dish_name": "Imported Pork Pepperoni Pizza",
        "description": "Traditional crust topped with Italian pork pepperoni and mozzarella cheese",
        "ingredients": "wheat dough, pork pepperoni, mozzarella cheese, tomato paste, olive oil, oregano",
        "price_pkr": 2400,
        "location": "DHA",
        "halal": False,
        "spice_level": "Mild",
        "allergens": json.dumps(["gluten", "dairy"]),
        "category": "Fast Food",
        "protein_g": 28,
        "availability": True,
        "cuisine": "Italian",
        "source": "Expat Club Menu 2026",
        "source_url": "https://expatbistro.demo.pk/menu/006",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_007",
        "restaurant_name": "Karachi Bun Kabab Corner",
        "dish_name": "Street Style Bun Kabab",
        "description": "Pan-fried spiced beef and lentil patty dipped in whipped egg foam in a toasted bun with mint chutney",
        "ingredients": "wheat bun, beef, split chickpeas, eggs, onions, mint chutney, chaat masala",
        "price_pkr": 350,
        "location": "Saddar",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps(["gluten", "eggs"]),
        "category": "Fast Food",
        "protein_g": 14,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Saddar Street Menu 2026",
        "source_url": "https://bunkabab.demo.pk/menu/007",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_008",
        "restaurant_name": "Bundu Khan",
        "dish_name": "Royal Shahi Tukra",
        "description": "Mughlai dessert of crisp ghee-fried bread soaked in cardamom saffron condensed milk with dry fruits",
        "ingredients": "wheat bread, condensed milk, ghee, sugar, almonds, pistachios, saffron, cardamom",
        "price_pkr": 650,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps(["gluten", "dairy", "tree nuts"]),
        "category": "Dessert",
        "protein_g": 6,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bundu Khan Sweets 2026",
        "source_url": "https://bundukhan.demo.pk/menu/008",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_009",
        "restaurant_name": "Anarkali Dhaba",
        "dish_name": "Mystery Special Daily Daal",
        "description": "Slow-cooked spiced yellow lentils tempered with red chilies and unverified oil",
        "ingredients": "yellow lentils, spices, turmeric, unverified oil, garlic, red chilies",
        "price_pkr": 400,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["unknown"]),
        "category": "Vegetarian",
        "protein_g": 12,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Anarkali Dhaba Daily Board 2026",
        "source_url": "https://anarkali.demo.pk/menu/009",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_010",
        "restaurant_name": "Café Zouk",
        "dish_name": "Crispy Golden Prawns",
        "description": "Deep-fried jumbo Arabian sea prawns in seasoned breadcrumb coating served with tartar sauce",
        "ingredients": "jumbo prawns, wheat breadcrumbs, eggs, garlic powder, tartar sauce, vegetable oil",
        "price_pkr": 2100,
        "location": "DHA",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps(["shellfish", "eggs", "gluten"]),
        "category": "Seafood",
        "protein_g": 30,
        "availability": True,
        "cuisine": "Continental",
        "source": "Café Zouk DHA Menu 2026",
        "source_url": "https://cafezouk.demo.pk/menu/010",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_011",
        "restaurant_name": "Lal Qila",
        "dish_name": "Grilled Jumbo Tiger Prawns",
        "description": "Marinated coastal prawns grilled over charcoal with crushed red pepper lemon and garlic",
        "ingredients": "tiger prawns, garlic, lemon, chili flakes, olive oil, sea salt",
        "price_pkr": 2450,
        "location": "Saddar",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["shellfish"]),
        "category": "Seafood",
        "protein_g": 34,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Lal Qila Saddar Menu 2026",
        "source_url": "https://lalqila.demo.pk/menu/011",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_012",
        "restaurant_name": "Student Biryani",
        "dish_name": "Traditional Mutton Dum Biryani",
        "description": "Layered aromatic basmati rice and tender mutton cooked with yogurt saffron and traditional biryani masala",
        "ingredients": "basmati rice, mutton, yogurt, fried onions, whole spices, saffron, ghee",
        "price_pkr": 980,
        "location": "Saddar",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps(["dairy"]),
        "category": "Rice",
        "protein_g": 28,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Student Biryani Saddar 2026",
        "source_url": "https://studentbiryani.demo.pk/menu/012",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_013",
        "restaurant_name": "Student Biryani",
        "dish_name": "Plain Steamed Basmati Rice",
        "description": "Fluffy steamed long-grain Pakistani basmati rice without additives or dairy",
        "ingredients": "long-grain basmati rice, water, sea salt, vegetable oil",
        "price_pkr": 300,
        "location": "Saddar",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps([]),
        "category": "Rice",
        "protein_g": 5,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Student Biryani Saddar 2026",
        "source_url": "https://studentbiryani.demo.pk/menu/013",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_014",
        "restaurant_name": "Bundu Khan",
        "dish_name": "Chicken Tikka Boti",
        "description": "Charcoal-grilled boneless chicken marinated in lemon juice red chili vinegar and crushed garlic",
        "ingredients": "boneless chicken, lemon juice, red chili, garlic, ginger, vinegar, vegetable oil",
        "price_pkr": 850,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps([]),
        "category": "BBQ",
        "protein_g": 35,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bundu Khan Gulberg 2026",
        "source_url": "https://bundukhan.demo.pk/menu/014",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_015",
        "restaurant_name": "Bhaiya Kabab",
        "dish_name": "Seekh Kabab Beef",
        "description": "Tender smoked skewers of minced beef spiced with coriander green chilies and raw papaya",
        "ingredients": "minced beef, onions, coriander, green chilies, papaya paste, cumin, cloves, vegetable oil",
        "price_pkr": 950,
        "location": "DHA",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps([]),
        "category": "BBQ",
        "protein_g": 32,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bhaiya Kabab DHA 2026",
        "source_url": "https://bhaiyakabab.demo.pk/menu/015",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_016",
        "restaurant_name": "Bundu Khan",
        "dish_name": "Chicken Malai Boti",
        "description": "Melt-in-mouth succulent chicken chunks marinated in thick heavy dairy cream yogurt and white pepper",
        "ingredients": "chicken thigh cubes, heavy dairy cream, yogurt, white pepper, green cardamoms, garlic",
        "price_pkr": 990,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps(["dairy"]),
        "category": "BBQ",
        "protein_g": 34,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bundu Khan Gulberg 2026",
        "source_url": "https://bundukhan.demo.pk/menu/016",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_017",
        "restaurant_name": "GymDiet PK",
        "dish_name": "High-Protein Roasted Chicken Quarters",
        "description": "Skinless bone-in roasted chicken leg quarters seasoned purely with lemon sea salt and wild oregano",
        "ingredients": "skinless chicken leg quarters, lemon, sea salt, oregano, black pepper, olive oil",
        "price_pkr": 950,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps([]),
        "category": "Chicken",
        "protein_g": 46,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "GymDiet PK Menu 2026",
        "source_url": "https://gymdiet.demo.pk/menu/017",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_018",
        "restaurant_name": "Village Dhaba",
        "dish_name": "Traditional Palak Paneer",
        "description": "Creamy spinach gravy simmered with fresh cottage cheese paneer cubes and whole roasted cumin",
        "ingredients": "fresh spinach, paneer cheese, dairy cream, cumin, garlic, green chilies, butter",
        "price_pkr": 890,
        "location": "F-7",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["dairy"]),
        "category": "Vegetarian",
        "protein_g": 18,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Village Dhaba F-7 2026",
        "source_url": "https://villagedhaba.demo.pk/menu/018",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_019",
        "restaurant_name": "Village Dhaba",
        "dish_name": "Aloo Palak Vegan",
        "description": "Freshly chopped spinach cooked tenderly with baby potatoes mustard oil cumin and minced garlic",
        "ingredients": "spinach, potatoes, mustard oil, cumin, garlic, green chilies, turmeric",
        "price_pkr": 650,
        "location": "F-7",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps([]),
        "category": "Vegetarian",
        "protein_g": 7,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Village Dhaba F-7 2026",
        "source_url": "https://villagedhaba.demo.pk/menu/019",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_020",
        "restaurant_name": "K-Bites Wings",
        "dish_name": "Soy Garlic Glazed Wings",
        "description": "Crispy fried chicken wings tossed in an authentic sticky Korean soy sauce garlic and honey glaze",
        "ingredients": "chicken wings, soy sauce, garlic, honey, sesame seeds, cornstarch, vegetable oil",
        "price_pkr": 1100,
        "location": "F-7",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["soy"]),
        "category": "Fast Food",
        "protein_g": 26,
        "availability": True,
        "cuisine": "Asian",
        "source": "K-Bites Wings F-7 2026",
        "source_url": "https://kbites.demo.pk/menu/020",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_021",
        "restaurant_name": "Johnny & Jugnu",
        "dish_name": "Gourmet Smash Beef Burger",
        "description": "Double smashed beef patties with melted cheddar cheese pickles and signature mustard mayo sauce in a brioche bun",
        "ingredients": "beef chuck, brioche bun, cheddar cheese, eggs, mustard, mayonnaise, pickles",
        "price_pkr": 1050,
        "location": "Johar Town",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps(["gluten", "dairy", "eggs"]),
        "category": "Fast Food",
        "protein_g": 31,
        "availability": True,
        "cuisine": "Fast Food",
        "source": "Johnny & Jugnu Menu 2026",
        "source_url": "https://johnnyjugnu.demo.pk/menu/021",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_022",
        "restaurant_name": "Johnny & Jugnu",
        "dish_name": "Naked Smash Beef Burger Lettuce Wrap",
        "description": "Double smashed pure beef patties wrapped cleanly in crisp iceberg lettuce with grilled onions and mustard",
        "ingredients": "100% pure beef chuck patties, iceberg lettuce, grilled onions, tomato slices, yellow mustard",
        "price_pkr": 990,
        "location": "Johar Town",
        "halal": True,
        "spice_level": "Medium",
        "allergens": json.dumps([]),
        "category": "Beef",
        "protein_g": 35,
        "availability": True,
        "cuisine": "Healthy",
        "source": "Johnny & Jugnu Menu 2026",
        "source_url": "https://johnnyjugnu.demo.pk/menu/022",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_023",
        "restaurant_name": "Sultan Turkish Bakers",
        "dish_name": "Nutty Baklava Delight",
        "description": "Crispy layered paper-thin filo pastry layered with crushed pistachios and walnuts drizzled with sugar butter syrup",
        "ingredients": "filo dough, pistachios, walnuts, butter, sugar syrup, lemon",
        "price_pkr": 850,
        "location": "DHA",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps(["gluten", "tree nuts", "dairy"]),
        "category": "Dessert",
        "protein_g": 8,
        "availability": True,
        "cuisine": "Middle Eastern",
        "source": "Sultan Turkish Bakers 2026",
        "source_url": "https://sultan.demo.pk/menu/023",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_024",
        "restaurant_name": "Food Street Canteen",
        "dish_name": "Chana Chaat Street Bowl",
        "description": "Zesty boiled chickpeas mixed with boiled potatoes diced onions tomatoes tamarind pulp and chaat masala",
        "ingredients": "chickpeas, potatoes, onions, tomatoes, tamarind pulp, green chilies, cumin, chaat masala",
        "price_pkr": 350,
        "location": "Saddar",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps([]),
        "category": "Vegetarian",
        "protein_g": 11,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Food Street Saddar 2026",
        "source_url": "https://foodstreet.demo.pk/menu/024",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_025",
        "restaurant_name": "Bashir Dar-ul-Mahi",
        "dish_name": "Lahori Fried Fish",
        "description": "Fresh Rahu river fish marinated in carom seed and roasted chickpea batter crisp-fried in mustard oil",
        "ingredients": "rahu fish, chickpea flour, carom seeds, red chili, garlic, lemon juice, mustard oil",
        "price_pkr": 1400,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps([]),
        "category": "Seafood",
        "protein_g": 32,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bashir Dar-ul-Mahi Gulberg 2026",
        "source_url": "https://bashirfish.demo.pk/menu/025",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_026",
        "restaurant_name": "Bundu Khan",
        "dish_name": "Tandoori Roti",
        "description": "Traditional flatbread made from stone-ground whole wheat flour baked on clay tandoor walls",
        "ingredients": "whole wheat flour, water, salt",
        "price_pkr": 50,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps(["gluten"]),
        "category": "Bread",
        "protein_g": 4,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bundu Khan Gulberg 2026",
        "source_url": "https://bundukhan.demo.pk/menu/026",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_027",
        "restaurant_name": "Bundu Khan",
        "dish_name": "Roghani Naan",
        "description": "Soft pillowy refined flour bread enriched with milk yogurt and ghee topped with toasted sesame seeds",
        "ingredients": "wheat flour, cow milk, yogurt, ghee, sesame seeds, yeast, salt",
        "price_pkr": 120,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps(["gluten", "dairy"]),
        "category": "Bread",
        "protein_g": 6,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Bundu Khan Gulberg 2026",
        "source_url": "https://bundukhan.demo.pk/menu/027",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_028",
        "restaurant_name": "GymDiet PK",
        "dish_name": "Plain Boiled Farm Eggs",
        "description": "Two hard-boiled farm fresh eggs served with crushed black pepper and sea salt",
        "ingredients": "farm chicken eggs, sea salt, black pepper",
        "price_pkr": 200,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps(["eggs"]),
        "category": "Chicken",
        "protein_g": 13,
        "availability": True,
        "cuisine": "Healthy",
        "source": "GymDiet PK Menu 2026",
        "source_url": "https://gymdiet.demo.pk/menu/028",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_029",
        "restaurant_name": "FitMeal Kitchen",
        "dish_name": "Keto Cauliflower Rice Chicken Bowl",
        "description": "Grated riced cauliflower stir-fried with diced grilled chicken breast bell peppers and cold-pressed olive oil",
        "ingredients": "cauliflower, chicken breast, olive oil, bell peppers, turmeric, black pepper, sea salt",
        "price_pkr": 1290,
        "location": "DHA",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps([]),
        "category": "Chicken",
        "protein_g": 40,
        "availability": True,
        "cuisine": "Healthy",
        "source": "FitMeal Kitchen Menu 2026",
        "source_url": "https://fitmeal.demo.pk/menu/029",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_030",
        "restaurant_name": "Waris Nihari",
        "dish_name": "Daal Mash Special",
        "description": "Split white lentils cooked to perfection and garnished with pure desi butter ghee ginger and green chilies",
        "ingredients": "split urad lentils, desi ghee, ginger, green chilies, coriander, cumin, onion",
        "price_pkr": 600,
        "location": "Saddar",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps(["dairy"]),
        "category": "Vegetarian",
        "protein_g": 14,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Waris Nihari Saddar 2026",
        "source_url": "https://warisnihari.demo.pk/menu/030",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_031",
        "restaurant_name": "Mei Kong Chinese",
        "dish_name": "Chicken Corn Soup",
        "description": "Classic comfort soup with shredded chicken sweet yellow corn kernels and delicate whisked egg ribbons",
        "ingredients": "chicken broth, sweet corn, eggs, cornstarch, vinegar, soy sauce, black pepper",
        "price_pkr": 550,
        "location": "Rawalpindi",
        "halal": True,
        "spice_level": "Mild",
        "allergens": json.dumps(["eggs", "soy"]),
        "category": "Soup",
        "protein_g": 16,
        "availability": True,
        "cuisine": "Chinese",
        "source": "Mei Kong Menu 2026",
        "source_url": "https://meikong.demo.pk/menu/031",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_032",
        "restaurant_name": "Yum Chinese & Thai",
        "dish_name": "Thai Red Prawn Curry",
        "description": "Succulent prawns simmered in fiery red coconut curry with lemongrass bamboo shoots and kaffir lime",
        "ingredients": "tiger prawns, coconut milk, red chili paste, bamboo shoots, lemongrass, fish sauce",
        "price_pkr": 2200,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps(["shellfish"]),
        "category": "Seafood",
        "protein_g": 28,
        "availability": True,
        "cuisine": "Thai",
        "source": "Yum Thai Menu 2026",
        "source_url": "https://yumthai.demo.pk/menu/032",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_033",
        "restaurant_name": "Karachi BBQ",
        "dish_name": "Chefs Secret Karahi",
        "description": "Special house recipe chicken karahi with undisclosed house gravy mix",
        "ingredients": "chicken, tomatoes, ginger, green chili, house secret masala blend",
        "price_pkr": 1200,
        "location": "Saddar",
        "halal": True,
        "spice_level": "Spicy",
        "allergens": json.dumps(["conflict"]),
        "category": "Chicken",
        "protein_g": 30,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Karachi BBQ Counter 2026; Allergen Alert Bulletin 2026",
        "source_url": "https://karachibbq.demo.pk/menu/033",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_034",
        "restaurant_name": "Monal Express",
        "dish_name": "Fresh Mint Lemonade",
        "description": "Chilled refreshing hand-squeezed lemon juice with fresh garden mint leaves and black salt",
        "ingredients": "fresh lemon juice, mint leaves, sugar, soda water, black salt, ice",
        "price_pkr": 350,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps([]),
        "category": "Beverage",
        "protein_g": 0,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Monal Express Gulberg 2026",
        "source_url": "https://monal.demo.pk/menu/034",
        "timestamp": "2026-09-28T10:00:00Z"
    },
    {
        "id": "dish_035",
        "restaurant_name": "Haveli Restaurant",
        "dish_name": "Badami Kheer",
        "description": "Slow-simmered basmati rice pudding in rich whole milk infused with green cardamom and crushed almonds",
        "ingredients": "whole milk, basmati rice, sugar, almonds, cardamom, kewra essence",
        "price_pkr": 500,
        "location": "Gulberg",
        "halal": True,
        "spice_level": "None",
        "allergens": json.dumps(["dairy", "tree nuts"]),
        "category": "Dessert",
        "protein_g": 7,
        "availability": True,
        "cuisine": "Pakistani",
        "source": "Haveli Restaurant Menu 2026",
        "source_url": "https://haveli.demo.pk/menu/035",
        "timestamp": "2026-09-28T10:00:00Z"
    }
]


def write_demo_csv(output_path: Path | str = "data/menu.csv") -> Path:
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(DEMO_RECORDS[0].keys())

    with open(out, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()
        for record in DEMO_RECORDS:
            writer.writerow(record)

    print(f"Successfully generated {len(DEMO_RECORDS)} items into {out.resolve()}")
    return out


if __name__ == "__main__":
    write_demo_csv()
